export const PRODUCTS = [
  {
    id: 0,
    name: "Basic T-Shirt",
    price: 20,
    description: "A simple, comfortable t-shirt made from 100% cotton.",
    image: "https://i.imgur.com/NmOgKzf.jpg",
    category: "T-Shirts",
    stock: 50,
  },
  {
    id: 1,
    name: "Pleated Skirt",
    price: 50,
    description: "A stylish pleated skirt that's perfect for a night out.",
    image: "https://i.imgur.com/yVStsNt.jpg",
    category: "Skirts",
    stock: 20,
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    price: 60,
    description:
      "A pair of slim fit jeans that will hug your body in all the right places.",
    image: "https://i.imgur.com/gmY6VPO.jpg",
    category: "Jeans",
    stock: 20,
  },
  {
    id: 3,
    name: "Casual Dress",
    price: 40,
    description: "A comfortable, casual dress that's perfect for a day out.",
    image: "https://i.imgur.com/vGrBNPr.jpg",
    category: "Dresses",
    stock: 30,
  },
  {
    id: 4,
    name: "Leather Jacket",
    price: 120,
    description: "A classic leather jacket that will never go out of style.",
    image: "https://i.imgur.com/zo9mOKH.jpg",
    category: "Jackets",
    stock: 15,
  },
  {
    id: 5,
    name: "Athletic Shorts",
    price: 25,
    description:
      "A pair of comfortable athletic shorts that are perfect for a workout.",
    image: "https://i.imgur.com/0ZYyv51.jpg",
    category: "Shorts",
    stock: 40,
  },
  {
    id: 6,
    name: "Printed Shirt",
    price: 35,
    description:
      "A stylish printed shirt that will make you stand out from the crowd.",
    image: "https://i.imgur.com/0bhvJ8p.jpg",
    category: "Shirts",
    stock: 25,
  },
  {
    id: 7,
    name: "Denim Skirt",
    price: 45,
    description: "A versatile denim skirt that can be dressed up or down.",
    image: "https://i.imgur.com/VuHhiRz.jpg",
    category: "Skirts",
    stock: 20,
  },
  {
    id: 8,
    name: "Sweatshirt",
    price: 30,
    description: "A cozy sweatshirt that's perfect for a lazy day.",
    image: "https://i.imgur.com/fp9Z3q3.jpg",
    category: "Sweatshirts",
    stock: 35,
  },
  {
    id: 9,
    name: "Slip-On Sneakers",
    price: 50,
    description:
      "A pair of comfortable slip-on sneakers that are easy to wear.",
    image: "https://i.imgur.com/tmrjvyh.jpg",
    category: "Shoes",
    stock: 30,
  },
  {
    id: 10,
    name: "Printed Dress",
    price: 50,
    description: "A stylish printed dress that's perfect for a night out.",
    image: "https://i.imgur.com/WNUKj18.jpg",
    category: "Dresses",
    stock: 15,
  },
  {
    id: 11,
    name: "Cargo Pants",
    price: 55,
    description:
      "A pair of cargo pants with plenty of pockets for all your essentials.",
    image: "https://i.imgur.com/v1tqMCI.jpg",
    category: "Pants",
    stock: 20,
  },
  {
    id: 12,
    name: "Cropped Sweater",
    price: 35,
    description: "A cozy cropped sweater that's perfect for layering.",
    image: "https://i.imgur.com/MSW5Q5c.jpg",
    category: "Sweaters",
    stock: 25,
  },
  {
    id: 13,
    name: "Fleece Jacket",
    price: 45,
    description: "A warm fleece jacket that's perfect for chilly days.",
    image: "https://i.imgur.com/hdKblCh.jpg",
    category: "Jackets",
    stock: 15,
  },
  {
    id: 14,
    name: "Floral Blouse",
    price: 30,
    description: "A lightweight floral blouse that's perfect for spring.",
    image: "https://i.imgur.com/njK63NN.jpg",
    category: "Blouses",
    stock: 30,
  },
  {
    id: 15,
    name: "Wool Coat",
    price: 100,
    description: "A classic wool coat that will keep you warm all winter.",
    image: "https://i.imgur.com/ACZM1jr.jpg",
    category: "Coats",
    stock: 10,
  },
  {
    id: 16,
    name: "Leather Boots",
    price: 80,
    description: "A pair of stylish leather boots that are perfect for fall.",
    image: "https://i.imgur.com/N2LLdNl.jpg",
    category: "Shoes",
    stock: 15,
  },
  {
    id: 17,
    name: "Maxi Dress",
    price: 60,
    description: "A flowy maxi dress that's perfect for a summer day.",
    image: "https://i.imgur.com/9v6HPbA.jpg",
    category: "Dresses",
    stock: 20,
  },
  {
    id: 18,
    name: "Striped Sweater",
    price: 40,
    description: "A cozy striped sweater that's perfect for a chilly day.",
    image: "https://i.imgur.com/pZJhnmZ.jpg",
    category: "Sweaters",
    stock: 25,
  },
  {
    id: 19,
    name: "Cargo Jacket",
    price: 65,
    description: "A lightweight cargo jacket that's perfect for spring.",
    image: "https://i.imgur.com/0gVJv8t.jpg",
    category: "Jackets",
    stock: 15,
  },
];
