export const products = [
  {
    id: 1,
    name: "Basic T-Shirt",
    price: 20,
    description: "A simple, comfortable t-shirt made from 100% cotton.",
    image: "https://i.imgur.com/NmOgKzf.jpg",
    category: "Shirts",
    stock: 50,
    dateAdded: "2023-05-01",
  },
  {
    id: 2,
    name: "V-Neck T-Shirt",
    price: 25,
    description:
      "A classic v-neck t-shirt made from soft and breathable fabric.",
    image: "https://i.imgur.com/vVewjUh.jpg",
    category: "Shirts",
    stock: 40,
    dateAdded: "2023-05-02",
  },
  {
    id: 3,
    name: "Graphic T-Shirt",
    price: 30,
    description: "A stylish graphic t-shirt that's perfect for casual wear.",
    image: "https://i.imgur.com/hB0XWYD.jpg",
    category: "Shirts",
    stock: 35,
    dateAdded: "2023-05-03",
  },
  {
    id: 4,
    name: "Sneakers",
    price: 80,
    description: "A pair of classic sneakers that go well with any outfit.",
    image: "https://i.imgur.com/yvNPAx7.jpg",
    category: "Shoes",
    stock: 20,
    dateAdded: "2023-05-02",
  },
  {
    id: 5,
    name: "Loafers",
    price: 100,
    description:
      "A pair of stylish loafers that are perfect for work or a night out.",
    image: "https://i.imgur.com/79J9XGv.jpg",
    category: "Shoes",
    stock: 15,
    dateAdded: "2023-05-03",
  },
  {
    id: 6,
    name: "Boots",
    price: 120,
    description:
      "A pair of rugged boots that will keep your feet warm and dry.",
    image: "https://i.imgur.com/m7AGmyJ.jpg",
    category: "Shoes",
    stock: 10,
    dateAdded: "2023-05-01",
  },
  {
    id: 7,
    name: "Jeans",
    price: 60,
    description: "A classic pair of jeans that will never go out of style.",
    image: "https://i.imgur.com/gmY6VPO.jpg",
    category: "Pants",
    stock: 25,
    dateAdded: "2023-05-04",
  },
  {
    id: 8,
    name: "Chinos",
    price: 70,
    description: "A versatile pair of chinos that can be dressed up or down.",
    image: "https://i.imgur.com/g7cPCNe.jpg",
    category: "Pants",
    stock: 20,
    dateAdded: "2023-05-03",
  },
  {
    id: 9,
    name: "Cargo Pants",
    price: 80,
    description:
      "A pair of cargo pants with plenty of pockets for all your essentials.",
    image: "https://i.imgur.com/v1tqMCI.jpg",
    category: "Pants",
    stock: 15,
    dateAdded: "2023-05-01",
  },
  {
    id: 10,
    name: "Denim Jacket",
    price: 100,
    description: "A classic denim jacket that's perfect for layering.",
    image: "https://i.imgur.com/l1lNWQI.jpg",
    category: "Shirts",
    stock: 10,
    dateAdded: "2023-05-01",
  },
  {
    id: 11,
    name: "Leather Boots",
    price: 150,
    description: "A pair of stylish leather boots that are perfect for fall.",
    image: "https://i.imgur.com/N2LLdNl.jpg",
    category: "Shoes",
    stock: 10,
    dateAdded: "2023-05-04",
  },
  {
    id: 12,
    name: "Sweatpants",
    price: 50,
    description:
      "A pair of comfortable sweatpants that are perfect for lounging.",
    image: "https://i.imgur.com/kmcmnlQ.jpg",
    category: "Pants",
    stock: 30,
    dateAdded: "2023-05-04",
  },
  {
    id: 13,
    name: "Sweatshirt",
    price: 60,
    description: "A cozy sweatshirt that's perfect for a lazy day.",
    image: "https://i.imgur.com/fp9Z3q3.jpg",
    category: "Shirts",
    stock: 20,
    dateAdded: "2023-05-04",
  },
  {
    id: 14,
    name: "Polo Shirt",
    price: 40,
    description: "A classic polo shirt that's perfect for a casual day.",
    image: "https://i.imgur.com/8omd1WF.jpg",
    category: "Shirts",
    stock: 25,
    dateAdded: "2023-05-04",
  },
  {
    id: 15,
    name: "Button-Down Shirt",
    price: 50,
    description: "A stylish button-down shirt that's perfect for any occasion.",
    image: "https://i.imgur.com/Ftq3rFp.jpg",
    category: "Shirts",
    stock: 20,
    dateAdded: "2023-05-04",
  },
  {
    id: 16,
    name: "Running Shoes",
    price: 120,
    description:
      "A pair of high-performance running shoes that will help you go the distance.",
    image: "https://i.imgur.com/t2aO8Nv.jpg",
    category: "Shoes",
    stock: 15,
    dateAdded: "2023-05-04",
  },
  {
    id: 17,
    name: "Dress Shoes",
    price: 100,
    description: "A pair of classic dress shoes that will elevate any outfit.",
    image: "https://i.imgur.com/ygjQoJi.jpg",
    category: "Shoes",
    stock: 20,
    dateAdded: "2023-05-04",
  },
  {
    id: 18,
    name: "Khaki Pants",
    price: 80,
    description:
      "A pair of khaki pants that are perfect for both work and play.",
    image: "https://i.imgur.com/nU6YhK6.jpg",
    category: "Pants",
    stock: 15,
    dateAdded: "2023-05-04",
  },
  {
    id: 19,
    name: "Cargo Shorts",
    price: 50,
    description:
      "A pair of cargo shorts with plenty of pockets for all your essentials.",
    image: "https://i.imgur.com/1k0lLcB.jpg",
    category: "Shorts",
    stock: 25,
    dateAdded: "2023-05-04",
  },
  {
    id: 20,
    name: "Sneaker Boots",
    price: 150,
    description:
      "A pair of stylish sneaker boots that are perfect for any weather.",
    image: "https://i.imgur.com/9bySvJL.jpg",
    category: "Shoes",
    stock: 10,
    dateAdded: "2023-05-04",
  },
];
